title: Engineer's blog
email: 19graff91@gmail.com
description: >-
  This is a repository for my thoughts, knowledge, and ideas that I want to share.
baseurl: "/"
url: "https://andreipiatrou.github.io"
twitter_username: graffinchik
github_username:  andreipiatrou

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      author: Andrei Piatrou
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
      toc_label: "On This Page"

include:
  - _pages

comments:
  provider: "disqus"
  disqus:
    shortname: "https-andreipiatrou-github-io"

analytics:
  provider: "google"
  google:
    tracking_id: UA-121799026-1
